apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - name: http
      nodePort: 30001 
      port: 80 
      targetPort: 80 
      protocol: TCP