apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: 767828724436.dkr.ecr.ap-northeast-2.amazonaws.com/hkit/kit:latest
          ports:
            - containerPort: 8080
